### ISSUE TITLE
Support for Babylon v.5.0

### ISSUE THREAD

**Issue by KonstantinKolesnik** [Blimster/babylon_dart_gen#1]
Any plans to upgrade to Babylon v.5.0?

**Comment by Blimster** [comment]
Hi @KonstantinKolesnik, there was no plan yet. But I will take a look, if it possible without much effort.

This repository is discontinued. Please, create a new issue at [babylon_dart](https://github.com/Blimster/babylon_dart).

PS: Wish you all the best in this tough time for your country and the people.
